### ISSUE TITLE
Cant Play custom songs with PPCounter installed

### ISSUE THREAD

**Issue by stylez-afk** [PulseLane/PPCounter#1]
Whenever I have PPCounter installed with Counters+, every time i try to go into a custom song it just says "Error Loading Data"

idk if this is an issue with my game or with the mod.

**Comment by PulseLane** [comment]
That's very strange - does this happen on every song, not just ranked songs? And does it still happen when you disable the mod in Counters+ settings? Logs would also be super helpful
