### ISSUE TITLE
Star rating isn't correct on some maps

### ISSUE THREAD

**Issue by duhby** [PulseLane/PPCounter#3]
**Description:**
On some songs, the star rating isn't correct causing the pp value to be lower than it should be.

**Steps to reproduce:**
1. Open the song 1fdfa (Electromagnetic Stealth Girl Born In Philadelphia)
2. Play the song or watch a replay
3. See that the pp value is lower than it should be on all difficulties but is correct in other maps

**System info:**
Game verison: 1.25.1

**Comment by PulseLane** [comment]
I have to manually update the star ratings and forgot to after the latest reweight.

Thanks for reporting, has been fixed now.
