### ISSUE TITLE
No settings for BeatLeader and AccSaber 

### ISSUE THREAD

**Issue by Henry9871** [PulseLane/PPCounter#5]
There are no settings in the mod menu, counters+ menu, or any menu to turn on BeatLeader and AccSaber support on 1.25.1. If you need anything please let me know.

**Comment by PulseLane** [comment]
Are you not seeing the PP Counter settings at all in Counters+, or just not those specific settings? If you're seeing settings, but not those then you didn't install the new version. If you're not seeing any settings then you likely didn't install the mod correctly but I would need logs to know what exactly went wrong.

**Comment by Henry9871** [comment]
I'm seeing the PP Counter settings in Counters+ but I'm just not seeing those specific settings. I made sure to download the newest Counters+ but it might be one of the mods interfering with it not sure. I will send my logs when I get home which should be in around 4ish hours.

**Comment by Henry9871** [comment]
[_latest.log](https://github.com/PulseLane/PPCounter/files/11550443/_latest.log)
Here is my latest log btw

**Comment by Henry9871** [comment]
Well I feel stupid now, I found out that I was dropping the new PP Counter plugin into my beat saber backup folder into my current folder. Thanks for your help.
