### ISSUE TITLE
PPCounter causing Beat Saber 1.29.1 not to load

### ISSUE THREAD

**Issue by SaltyShadow0** [PulseLane/PPCounter#6]
I don't mean to bust your balls or anything but my game has been having issues trying to load with the latest version of your mod.

I did originally make a post in BSMG about this but I might as well bring this to you as well and get your opinion.

Every time PPCounter is installed and I try and run the game, all I do get is a black screen and it will not proceed from that screen.

**Comment by PulseLane** [comment]
I need logs to be able to diagnose the issue here

**Comment by SaltyShadow0** [comment]
Here you go!
[_latest.log](https://github.com/PulseLane/PPCounter/files/11579731/_latest.log)

**Comment by PulseLane** [comment]
Latest release should fix it https://github.com/PulseLane/PPCounter/releases/tag/2.0.1

**Comment by SaltyShadow0** [comment]
Thank you very much! The game loads as it should and the mod is working properly!
